project:
  type: website

website:
  title: "CNG Tutorials"
  repo-url: https://github.com/VorGeo/cng-onboarding
  repo-actions: [source, issue]
  reader-mode: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "S2 from AWS"
        href: tutorials/s2-from-aws.qmd
      - text: "Landsat from MSPC"
        href: tutorials/landsat-from-mspc.qmd
format:
  html:
    theme:  # pandoc, default, flatly, darkly, sketchy, sandstone, cyborg, zephyr
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

execute:
  freeze: auto
