name: nbstripout
on: [ push, pull_request ]
jobs:
  strip_metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install nbstripout
        run: pip install nbstripout

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Strip metadata from notebooks with verbose logging
        run: |
          echo "Stripping metadata from notebooks..."
          find . -name "*.ipynb" | while read notebook; do
            echo "Processing $notebook"
            nbstripout --keep-count --keep-output --drop-empty-cells "$notebook"
            git add "$notebook"
            if git status --porcelain | grep -E '^(A|M)'; then
              echo "New files detected. Committing changes..."
              git commit -m "Strip metadata from $notebook"
            else
              echo "No new files to commit."
            fi
          done

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin HEAD
